variable "env" {}
variable "public_key" {}
variable "ami" {}
variable "instance_type" {}
variable "security_group_web" {}
variable "subnet_1_app" {}
variable "subnet_2_app" {}
variable "iam_profile" {}
variable "awsrds_endpoint" {}
variable "username" {}
variable "password" {}
variable "root_password" {}
